# vPet dev workflow
# make help to see all targets

PY := python3

# Subdirs of build/ that are generated by build.py
BUILD_OUTPUT := Baby Rookie Champion Ultimate Mega Egg Background UI

.PHONY: help build deploy sim test clean all

help:
	@echo "vPet dev workflow"
	@echo ""
	@echo "  make build    src/ + assets/ → build/  (clean rebuild)"
	@echo "  make deploy   build/ → /Volumes/CIRCUITPY/  (the Pico)"
	@echo "  make sim      Run the vPet in a pygame window on Mac"
	@echo "  make test     Run pytest in tests/"
	@echo "  make all      clean + build + test + deploy"
	@echo "  make clean    Remove everything in build/ except code.py and settings.toml"

build: clean
	$(PY) scripts/build.py

deploy: build
	$(PY) scripts/deploy.py

sim:
	$(PY) scripts/simulator.py

test:
	$(PY) -m pytest tests/ -v

all: build test deploy

clean:
	@echo "  cleaning build/ (except code.py, settings.toml)..."
	@for d in $(BUILD_OUTPUT); do \
		if [ -d "build/$$d" ]; then rm -rf "build/$$d"; fi; \
	done
	@rm -rf build/lib
