#include <unity.h>

#include "vpet/Input.h"

using vpet::ButtonSample;
using vpet::Input;
using vpet::InputEvent;

void test_feed_updates_stats_once_when_animation_completes();
void test_training_updates_effort_once();
void test_new_pet_starts_as_egg_and_baby_cannot_attack();
void test_persisted_species_values_remain_compatible();
void test_dragfiremon_moves_with_fly_state();
void test_action_animation_returns_to_idle();
void test_sleep_loops_until_explicit_wake();
void test_dragfiremon_sleep_loops_lying_frames();
void test_sparkmon_evolution_uses_sixteen_frames();
void test_dragfiremon_idle_keeps_full_sheet();
void test_egg_idle_loops_intact_sheet();
void test_egg_hatch_plays_break_frames_once();
void test_baby_animates_after_leaving_egg_hatch();
void test_battle_reaction_picks_combat_sheet();
void test_punching_bag_stays_inside_bottom_edge();
void test_call_cues_the_matching_care_icon();
void test_call_blink_toggles_every_400ms();
void test_menu_opens_expected_panels();
void test_rest_icon_opens_rest_panel();
void test_cold_mode_freezes_decay_and_blocks_calls();
void test_backup_parks_current_pet_and_starts_egg();
void test_backup_swap_restores_parked_pet();
void test_next_moves_options_cursor();
void test_options_next_wraps_like_header_menu();
void test_back_in_options_is_ignored();
void test_force_next_form_walks_the_line();
void test_use_item_spends_stock_and_applies_stat();
void test_use_item_empty_and_egg_do_not_change_stats();
void test_empty_items_disappear_from_inventory_list();
void test_status_next_cycles_four_pages();
void test_roll_dna_differs_and_is_never_zero();
void test_ivs_read_dna_nibbles();
void test_combat_stat_uses_iv_ev_formula();
void test_care_and_items_gain_ev_with_caps();
void test_overfeed_does_not_gain_ev();
void test_reset_to_egg_clears_dna_and_ev();
void test_evolution_keeps_dna_and_ev();
void test_settings_persist_dna_and_ev();
void test_schema2_rookie_synthesizes_stable_dna();
void test_helix_helpers_use_dna_or_gray();
void test_hunger_and_energy_map_to_four_hearts();
void test_win_ratio_is_zero_until_a_battle_is_played();
void test_settings_persist_inventory_counts();
void test_missing_inventory_keys_use_defaults();
void test_next_walks_color_line_then_dark_branch();
void test_hidden_branch_does_not_reveal_identity();
void test_held_next_repeats_while_held();
void test_action_on_known_evolution_opens_detail();
void test_action_on_hidden_evolution_stays_on_tree();
void test_reach_requirements_use_incoming_rule();
void test_next_wraps_inventory_like_options();
void test_action_on_inventory_item_stays_in_menu();
void test_missing_save_keeps_current_species_discovered();
void test_settings_persist_bluetooth_preference();
void test_first_advertise_configures_payload_later_restarts_only();
void test_date_year_minus_steps_down();
void test_date_year_plus_wraps_from_max();
void test_date_year_minus_wraps_from_min();
void test_date_next_wraps_like_options();
void test_date_save_and_back_rows();
void test_time_hour_minus_wraps_to_23();
void test_status_clock_uses_saved_date_and_time();
void test_date_labels_use_spanish();
void test_status_labels_switch_with_language();
void test_options_labels_switch_with_language();
void test_egg_is_not_in_evolution_check();
void test_sparkmon_one_second_short_does_not_evolve();
void test_sparkmon_timer_and_cm_zero_evolves_to_firemon();
void test_sparkmon_timer_with_two_cm_does_not_evolve();
void test_firemon_timer_with_low_bars_does_not_evolve();
void test_firemon_timer_with_ready_bars_evolves_to_flamemon();
void test_flamemon_timer_with_fourteen_battles_does_not_evolve();
void test_flamemon_timer_with_fifteen_battles_evolves_to_dragfiremon();
void test_scale_600_evolves_sparkmon_at_seventy_three_seconds();
void test_ignored_hunger_call_adds_one_care_mistake();
void test_bedtime_without_sleep_starts_lights_call();
void test_asleep_at_bedtime_does_not_start_lights_call();
void test_rest_clears_lights_call();
void test_ignored_lights_call_adds_one_care_mistake();
void test_evolution_apply_resets_care_and_keeps_wins();
void test_force_skips_thresholds();
void test_schema1_load_uses_schema2_defaults_and_does_not_evolve();
void test_settings_persist_care_trace();
void test_unsupported_schema_is_rejected();
void test_care_event_ring_wraps();
void test_snapshot_is_twenty_bytes();
void test_force_from_ultimate_restarts_as_egg();
void test_missing_life_key_restarts_as_egg();
void test_overfeed_once_when_full_is_not_a_care_mistake();
void test_second_feed_while_full_is_rejected();
void test_hunger_drop_allows_another_overfeed();
void test_meat_item_blocked_after_overfeed();
void test_wake_at_night_adds_care_mistake();
void test_wake_during_day_does_not_add_care_mistake();
void test_egg_wake_does_not_add_care_mistake();
void test_protein_every_four_uses_raises_overdose_and_dp();
void test_medkit_heals_injury_and_is_blocked_when_healthy();
void test_four_trains_make_one_effort_heart();
void test_battle_requires_dp_and_records_win();
void test_battle_loss_injures_and_medkit_clears_it();
void test_fifteen_injuries_kill_and_grave_restarts_egg();
void test_six_hours_injured_kills();
void test_rest_restores_one_dp();

void test_short_next_press() {
    Input input(25, 2000);
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 130));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 160));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 180));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 210));
}

void test_deliberate_next_press_under_two_seconds_stays_next() {
    Input input(25, 2000);
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 400));
    input.poll({false, false}, 400);
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 430));
}

void test_held_next_repeats_while_held() {
    Input input(25, 2000);
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 419));
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 420));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 599));
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 600));
}

void test_long_next_press_becomes_back() {
    Input input(25, 2000);
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 100));
    TEST_ASSERT_EQUAL(InputEvent::Back, input.poll({true, false}, 2100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 2200));
    input.poll({false, false}, 2230);
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 2260));
}

void test_action_has_no_long_press_mapping() {
    Input input(25, 700);
    TEST_ASSERT_EQUAL(InputEvent::Action, input.poll({false, true}, 100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, true}, 1000));
    input.poll({false, false}, 1000);
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 1030));
}

void test_noisy_next_press_is_emitted_once() {
    Input input(25, 2000);
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 100));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 105));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 110));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({true, false}, 160));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 190));
    TEST_ASSERT_EQUAL(InputEvent::None, input.poll({false, false}, 220));
    TEST_ASSERT_EQUAL(InputEvent::Next, input.poll({true, false}, 230));
}

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_short_next_press);
    RUN_TEST(test_deliberate_next_press_under_two_seconds_stays_next);
    RUN_TEST(test_held_next_repeats_while_held);
    RUN_TEST(test_long_next_press_becomes_back);
    RUN_TEST(test_action_has_no_long_press_mapping);
    RUN_TEST(test_noisy_next_press_is_emitted_once);
    RUN_TEST(test_feed_updates_stats_once_when_animation_completes);
    RUN_TEST(test_training_updates_effort_once);
    RUN_TEST(test_new_pet_starts_as_egg_and_baby_cannot_attack);
    RUN_TEST(test_persisted_species_values_remain_compatible);
    RUN_TEST(test_dragfiremon_moves_with_fly_state);
    RUN_TEST(test_action_animation_returns_to_idle);
    RUN_TEST(test_sleep_loops_until_explicit_wake);
    RUN_TEST(test_dragfiremon_sleep_loops_lying_frames);
    RUN_TEST(test_sparkmon_evolution_uses_sixteen_frames);
    RUN_TEST(test_dragfiremon_idle_keeps_full_sheet);
    RUN_TEST(test_egg_idle_loops_intact_sheet);
    RUN_TEST(test_egg_hatch_plays_break_frames_once);
    RUN_TEST(test_baby_animates_after_leaving_egg_hatch);
    RUN_TEST(test_battle_reaction_picks_combat_sheet);
    RUN_TEST(test_punching_bag_stays_inside_bottom_edge);
    RUN_TEST(test_call_cues_the_matching_care_icon);
    RUN_TEST(test_call_blink_toggles_every_400ms);
    RUN_TEST(test_menu_opens_expected_panels);
    RUN_TEST(test_rest_icon_opens_rest_panel);
    RUN_TEST(test_cold_mode_freezes_decay_and_blocks_calls);
    RUN_TEST(test_backup_parks_current_pet_and_starts_egg);
    RUN_TEST(test_backup_swap_restores_parked_pet);
    RUN_TEST(test_next_moves_options_cursor);
    RUN_TEST(test_options_next_wraps_like_header_menu);
    RUN_TEST(test_back_in_options_is_ignored);
    RUN_TEST(test_force_next_form_walks_the_line);
    RUN_TEST(test_use_item_spends_stock_and_applies_stat);
    RUN_TEST(test_use_item_empty_and_egg_do_not_change_stats);
    RUN_TEST(test_empty_items_disappear_from_inventory_list);
    RUN_TEST(test_status_next_cycles_four_pages);
    RUN_TEST(test_roll_dna_differs_and_is_never_zero);
    RUN_TEST(test_ivs_read_dna_nibbles);
    RUN_TEST(test_combat_stat_uses_iv_ev_formula);
    RUN_TEST(test_care_and_items_gain_ev_with_caps);
    RUN_TEST(test_overfeed_does_not_gain_ev);
    RUN_TEST(test_reset_to_egg_clears_dna_and_ev);
    RUN_TEST(test_evolution_keeps_dna_and_ev);
    RUN_TEST(test_settings_persist_dna_and_ev);
    RUN_TEST(test_schema2_rookie_synthesizes_stable_dna);
    RUN_TEST(test_helix_helpers_use_dna_or_gray);
    RUN_TEST(test_hunger_and_energy_map_to_four_hearts);
    RUN_TEST(test_win_ratio_is_zero_until_a_battle_is_played);
    RUN_TEST(test_settings_persist_inventory_counts);
    RUN_TEST(test_missing_inventory_keys_use_defaults);
    RUN_TEST(test_next_walks_color_line_then_dark_branch);
    RUN_TEST(test_hidden_branch_does_not_reveal_identity);
    RUN_TEST(test_action_on_known_evolution_opens_detail);
    RUN_TEST(test_action_on_hidden_evolution_stays_on_tree);
    RUN_TEST(test_reach_requirements_use_incoming_rule);
    RUN_TEST(test_next_wraps_inventory_like_options);
    RUN_TEST(test_action_on_inventory_item_stays_in_menu);
    RUN_TEST(test_missing_save_keeps_current_species_discovered);
    RUN_TEST(test_settings_persist_bluetooth_preference);
    RUN_TEST(test_first_advertise_configures_payload_later_restarts_only);
    RUN_TEST(test_date_year_minus_steps_down);
    RUN_TEST(test_date_year_plus_wraps_from_max);
    RUN_TEST(test_date_year_minus_wraps_from_min);
    RUN_TEST(test_date_next_wraps_like_options);
    RUN_TEST(test_date_save_and_back_rows);
    RUN_TEST(test_time_hour_minus_wraps_to_23);
    RUN_TEST(test_status_clock_uses_saved_date_and_time);
    RUN_TEST(test_date_labels_use_spanish);
    RUN_TEST(test_status_labels_switch_with_language);
    RUN_TEST(test_options_labels_switch_with_language);
    RUN_TEST(test_egg_is_not_in_evolution_check);
    RUN_TEST(test_sparkmon_one_second_short_does_not_evolve);
    RUN_TEST(test_sparkmon_timer_and_cm_zero_evolves_to_firemon);
    RUN_TEST(test_sparkmon_timer_with_two_cm_does_not_evolve);
    RUN_TEST(test_firemon_timer_with_low_bars_does_not_evolve);
    RUN_TEST(test_firemon_timer_with_ready_bars_evolves_to_flamemon);
    RUN_TEST(test_flamemon_timer_with_fourteen_battles_does_not_evolve);
    RUN_TEST(test_flamemon_timer_with_fifteen_battles_evolves_to_dragfiremon);
    RUN_TEST(test_scale_600_evolves_sparkmon_at_seventy_three_seconds);
    RUN_TEST(test_ignored_hunger_call_adds_one_care_mistake);
    RUN_TEST(test_bedtime_without_sleep_starts_lights_call);
    RUN_TEST(test_asleep_at_bedtime_does_not_start_lights_call);
    RUN_TEST(test_rest_clears_lights_call);
    RUN_TEST(test_ignored_lights_call_adds_one_care_mistake);
    RUN_TEST(test_evolution_apply_resets_care_and_keeps_wins);
    RUN_TEST(test_force_skips_thresholds);
    RUN_TEST(test_schema1_load_uses_schema2_defaults_and_does_not_evolve);
    RUN_TEST(test_settings_persist_care_trace);
    RUN_TEST(test_unsupported_schema_is_rejected);
    RUN_TEST(test_care_event_ring_wraps);
    RUN_TEST(test_snapshot_is_twenty_bytes);
    RUN_TEST(test_force_from_ultimate_restarts_as_egg);
    RUN_TEST(test_missing_life_key_restarts_as_egg);
    RUN_TEST(test_overfeed_once_when_full_is_not_a_care_mistake);
    RUN_TEST(test_second_feed_while_full_is_rejected);
    RUN_TEST(test_hunger_drop_allows_another_overfeed);
    RUN_TEST(test_meat_item_blocked_after_overfeed);
    RUN_TEST(test_wake_at_night_adds_care_mistake);
    RUN_TEST(test_wake_during_day_does_not_add_care_mistake);
    RUN_TEST(test_egg_wake_does_not_add_care_mistake);
    RUN_TEST(test_protein_every_four_uses_raises_overdose_and_dp);
    RUN_TEST(test_medkit_heals_injury_and_is_blocked_when_healthy);
    RUN_TEST(test_four_trains_make_one_effort_heart);
    RUN_TEST(test_battle_requires_dp_and_records_win);
    RUN_TEST(test_battle_loss_injures_and_medkit_clears_it);
    RUN_TEST(test_fifteen_injuries_kill_and_grave_restarts_egg);
    RUN_TEST(test_six_hours_injured_kills);
    RUN_TEST(test_rest_restores_one_dp);
    return UNITY_END();
}
