#!/usr/bin/env python3
"""Flatten src/ into a single code.py for CircuitPython.

CircuitPython doesn't support `from package.module import X` for user code
on the root FS, so we concatenate everything into one file.

Output: build/code.py
"""
import os
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
BUILD = ROOT / "build"

# Order matters: dependencies first
ORDER = [
    SRC / "hal.py",
    SRC / "core" / "pet.py",
    SRC / "core" / "evolution.py",
    SRC / "core" / "battle.py",
    SRC / "core" / "save.py",
    SRC / "ui" / "sprites.py",
    SRC / "ui" / "widgets.py",
    SRC / "app.py",
]


def flatten():
    """Concatenate all source files into a single Python module."""
    BUILD.mkdir(exist_ok=True)
    out = BUILD / "code.py"

    parts = [
        '"""vPet - generated by scripts/build.py from src/. Do not edit directly."""',
        "",
    ]

    for path in ORDER:
        if not path.exists():
            print(f"  WARN: missing {path}")
            continue
        content = path.read_text()
        # Remove the original module docstring (we already have one at the top)
        content = re.sub(r'^"""[^"]*"""\s*\n', '', content, count=1)
        # Remove import lines that reference other src/ modules — we inline them
        content = re.sub(r'^(?:from|import)\s+[a-z_]+(?:\.[a-z_]+)*\s*$',
                         '# (import flattened)', content, flags=re.MULTILINE)
        content = re.sub(r'^(?:from|import)\s+[a-z_]+(?:\.[a-z_]+)*\s+import\s+.*$',
                         '# (import flattened)', content, flags=re.MULTILINE)
        parts.append(f"# === {path.relative_to(SRC)} ===")
        parts.append(content)
        parts.append("")

    out.write_text("\n".join(parts))
    print(f"  wrote {out} ({out.stat().st_size} bytes)")


def main():
    print("=== build.py ===")
    flatten()
    print("OK")


if __name__ == "__main__":
    main()
