#!/usr/bin/env python3
"""Flatten src/ into a single code.py for CircuitPython + collect runtime assets.

This script does 3 things:
  1. Concatenates src/*.py into build/code.py (CircuitPython doesn't support
     multi-file user modules on the root FS).
  2. Walks assets/digimon/<species>/ and copies the BMPs into build/<Species>/
     so the runtime can find them at /<Species>/<state>.bmp.
  3. Walks assets/ui/ and assets/backgrounds/ and copies the BMPs into build/UI/
     and build/Background/ respectively.

The deploy.py script later copies build/ to /Volumes/CIRCUITPY/.

Asset source-of-truth:
  - assets/digimon/<line>/<stage>/<state>/<file>.bmp  →  build/<Stage>/<file>.bmp
  - assets/ui/buttons/<name>.bmp                      →  build/UI/buttons/<name>.bmp
  - assets/ui/icons/<name>.bmp                        →  build/UI/icons/<name>.bmp
  - assets/backgrounds/<name>.bmp                     →  build/Background/<name>.bmp
"""
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
BUILD = ROOT / "build"
ASSETS = ROOT / "assets"

# Source file order for flattening
ORDER = [
    SRC / "hal.py",
    SRC / "core" / "pet.py",
    SRC / "core" / "evolution.py",
    SRC / "core" / "battle.py",
    SRC / "core" / "save.py",
    SRC / "ui" / "sprites.py",
    SRC / "ui" / "widgets.py",
    SRC / "app.py",
]


def flatten_code():
    """Concatenate all source files into a single Python module."""
    BUILD.mkdir(exist_ok=True)
    out = BUILD / "code.py"
    parts = ['"""vPet - generated by scripts/build.py from src/. Do not edit directly."""', ""]
    for path in ORDER:
        if not path.exists():
            print(f"  WARN: missing {path}")
            continue
        content = path.read_text()
        # Remove original docstring at top
        content = re.sub(r'^"""[^"]*"""\s*\n', '', content, count=1)
        # Comment-out intra-src imports (already flattened)
        content = re.sub(r'^(?:from|import)\s+[a-z_]+(?:\.[a-z_]+)*\s*$',
                         '# (import flattened)', content, flags=re.MULTILINE)
        content = re.sub(r'^(?:from|import)\s+[a-z_]+(?:\.[a-z_]+)*\s+import\s+.*$',
                         '# (import flattened)', content, flags=re.MULTILINE)
        parts.append(f"# === {path.relative_to(SRC)} ===")
        parts.append(content)
        parts.append("")
    out.write_text("\n".join(parts))
    print(f"  wrote {out} ({out.stat().st_size} bytes)")


def title_case(name):
    """Convert 'my_digimon' or 'my-digimon' to 'MyDigimon'."""
    return "".join(w.capitalize() for w in re.split(r'[_\-]', name))


def collect_digimon_sprites():
    """Copy assets/digimon/<line>/<stage>/<state>/<file>.bmp → build/<Stage>/<file>.bmp.

    Layout:
      assets/digimon/<line>/<stage>/<state>/<file>.bmp
        → build/<Stage>/<file>.bmp

    The <line> wrapper and the <state> subdirectory are both collapsed. The
    device runtime loads sprites by stage name, not by line, so multiple
    digimon lines can share the same device folders (e.g. /Egg/ is the egg
    for any line).

    Example:
      assets/digimon/digimon1/egg/idle/hatch_atlas.bmp
        → build/Egg/hatch_atlas.bmp
      assets/digimon/digimon1/baby/eat/eat_1.bmp
        → build/Baby/eat_1.bmp
      assets/digimon/digimon2/rookie/idle/idle_atlas.bmp
        → build/Rookie/idle_atlas.bmp   (overwrites if same name)
    """
    src_dir = ASSETS / "digimon"
    if not src_dir.exists():
        print(f"  WARN: {src_dir} not present")
        return
    n = 0
    # Find all lines (subdirs of digimon/)
    for line_dir in sorted(src_dir.iterdir()):
        if not line_dir.is_dir():
            continue
        if line_dir.name.startswith("."):
            continue
        # Find all stages within this line
        for stage_dir in sorted(line_dir.iterdir()):
            if not stage_dir.is_dir():
                continue
            if stage_dir.name.startswith("."):
                continue
            target_dir = BUILD / title_case(stage_dir.name)
            target_dir.mkdir(parents=True, exist_ok=True)
            # Find all BMPs in this stage's subdirs
            for bmp in stage_dir.rglob("*.bmp"):
                rel = bmp.relative_to(stage_dir)
                # Drop the first dir (the state) so the file goes directly into
                # build/<Stage>/. Multi-level state subdirs (e.g. for state-variants)
                # are preserved.
                parts = rel.parts
                if len(parts) >= 2:
                    target = target_dir / Path(*parts[1:])
                else:
                    target = target_dir / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(bmp, target)
                n += 1
    print(f"  collected {n} digimon sprite(s) from {src_dir}")


def collect_ui():
    """Copy assets/ui/buttons/*.bmp → build/UI/buttons/*.bmp and same for icons."""
    src_dir = ASSETS / "ui"
    if not src_dir.exists():
        print(f"  WARN: {src_dir} not present")
        return
    n = 0
    target_root = BUILD / "UI"
    for sub in ("buttons", "icons"):
        src_sub = src_dir / sub
        if not src_sub.exists():
            continue
        target_sub = target_root / sub
        target_sub.mkdir(parents=True, exist_ok=True)
        for bmp in src_sub.rglob("*.bmp"):
            rel = bmp.relative_to(src_sub)
            target = target_sub / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(bmp, target)
            n += 1
    print(f"  collected {n} UI asset(s) from {src_dir}")


def collect_backgrounds():
    """Copy assets/backgrounds/*.bmp → build/Background/*.bmp."""
    src_dir = ASSETS / "backgrounds"
    if not src_dir.exists():
        print(f"  WARN: {src_dir} not present")
        return
    target = BUILD / "Background"
    target.mkdir(parents=True, exist_ok=True)
    n = 0
    for bmp in src_dir.rglob("*.bmp"):
        shutil.copy2(bmp, target / bmp.name)
        n += 1
    print(f"  collected {n} background(s) from {src_dir}")


def copy_settings():
    """Copy settings.toml to build/ (if it exists at repo root)."""
    src = ROOT / "settings.toml"
    if src.exists():
        shutil.copy2(src, BUILD / "settings.toml")
        print(f"  copied settings.toml")


def main():
    print("=== build.py ===")
    print("[1/4] Flattening src/ → build/code.py")
    flatten_code()
    print("[2/4] Collecting digimon sprites")
    collect_digimon_sprites()
    print("[3/4] Collecting UI assets")
    collect_ui()
    print("[4/4] Collecting backgrounds + settings")
    collect_backgrounds()
    copy_settings()
    print("OK")


if __name__ == "__main__":
    main()
